### ISSUE TITLE
why not use cmake?

### ISSUE THREAD

**Issue by bluealert** [cpv-project/cpv-cql-driver#12]
Use cmake to manage the project, can make more people understand the code more easily using CLion.

**Comment by 303248153** [comment]
Hello, I did use cmake for build both library and tests:
https://github.com/cpv-project/cpv-cql-driver/blob/master/src/CMakeLists.txt
https://github.com/cpv-project/cpv-cql-driver/blob/master/tests/CMakeLists.txt
But I didn't test with CLion.

**Comment by bluealert** [comment]
If you use CLion to open the src directory, you won't be satisfied. :)

**Comment by bluealert** [comment]
https://github.com/bluealert/Seastar-cmake
I have use CMake to manage the build of seastar, but the apps all crashed at a same point when start. I can't find the reason now.

@303248153 @avikivity

![screenshot from 2018-03-25 04-06-10](https://user-images.githubusercontent.com/2254200/37868479-e2e00ba4-2fe1-11e8-9bae-9ab68c24d770.png)

**Comment by 303248153** [comment]
I do a little fix with CMakeLists.txt, now CLion should able to locate the header files correctly.
But CLion didn't supports c++17 well, so there still remain many false positives.
![screenshot](https://user-images.githubusercontent.com/16222094/37886577-c1946522-30ee-11e8-9d31-d13f29bdd972.jpg)

As for seastar framework itself, they use ninja not cmake, you could open a issue on their [repository](https://github.com/scylladb/seastar).

**Comment by bluealert** [comment]
They can use cmake and then `cmake -GNinja`. @avikivity

**Comment by 303248153** [comment]
Since this library actually use cmake and editable with clion, I'm going to close this issue. For further discussion please move to https://github.com/scylladb/seastar
