### ISSUE TITLE
Better support for prepared statement

### ISSUE THREAD

**Issue by 303248153** [cpv-project/cpv-cql-driver#13]
For better performance, I should rethink the design about prepared statement.
For high level, there two design:

Prepare the statement explicitly:

``` c++
session.prepare("select name from abc where id = ?").then([] (cql::PreparedQuery query) {
    auto command = cql::Command(query)
        .addParameters(cql::Int(123));
    return session.query(std::move(command));
}).then([] (cql::ResultSet result) {
    // ...
});
```

Prepare the statement implicitly (like the batch command):

``` c++
auto command = cql::Command("select name from abc where id = ?")
    .prepareQuery()
    .addParameters(cql::Int(123));
session.query(std::move(command)).then([] (cql::ResultSet result) {
    // ...
});
```

I personally prefer the implicitly solution, it's easier to manage and reduce user work, but it needs a hash map to associate query string and prepared query id.

--------------------------------------------------------

For low level, things are complicated.
For `Session::query` and `Session::execute` I can do this:

``` text
connection = pool.getConnection()
node = connection.node
id = preparedQuery[node]
if  (id == nullptr) {
    id = connection.send(prepareMessage)
    preparedQuery[node] = id
}
result = connection.send(executeMessage)
if (result.error && result.errorCode == 0x2500) {
    id = connection.send(prepareMessage)
    preparedQuery[node] = id
    result = connection.send(executeMessage)
}
return result
```

But for `Session::batchExecute`, I don't know what's the best solution.

For example I send a batch with prepared statement A, B, C,
A is prepared on the node but B and C does not,
will the server execute statement A, made the side effect, then return an unprepared error?

And since 0x2500 only return a single id in [short bytes], I need to retry many times like:

- send a batch with prepared statement A, B, C
- server return an error indicates B has not prepared
- prepare B
- send a batch with prepared statement A, B, C
- server return an error indicates C has not prepared
- prepare C
- send a batch with prepared statement A, B, C
- success

Compare to the solution I'm using for now (version 0.1):

- prepare A anyway
- prepare B anyway
- prepare C anyway
- send a batch with prepared statement A, B, C

--------------------------------------------------------

Improve the prepare process:

For now prepare multiple statements I will wait for each response before next request:

- send PREPARE
- wait RESULT or ERROR
- send PREPARE
- wait RESULT or ERROR
- send PREPARE
- wait RESULT or ERROR

I can change it to (pipeline):

- send PREPARE
- send PREPARE
- send PREPARE
- wait RESULT or ERROR
- wait RESULT or ERROR
- wait RESULT or ERROR

**Comment by 303248153** [comment]
> For example I send a batch with prepared statement A, B, C,
> A is prepared on the node but B and C does not,
> will the server execute statement A, made the side effect, then return an unprepared error?

Actually tested, no side effects in this situation, the server won't execute A if B or C is not prepared.

Improved retry flow:

- send a batch with prepared statement A, B, C
- server return an error indicates B has not prepared
- prepare A, B, C (the node is likely to have restarted)
- send a batch with prepared statement A, B, C
- success

Now all problems are clear, I would do this in the next few days.

**Comment by 303248153** [comment]
completed, examples:

``` c++
cql::SessionFactory sessionFactory(
	cql::SessionConfiguration()
		.setDefaultKeySpace("system")
		.setPrepareAllQueries(true),
	cql::NodeCollection::create({
		cql::NodeConfiguration()
			.setAddress("127.0.0.1", 9043)
	}));
auto session = sessionFactory.getSession();
auto command = cql::Command("select * from batchlog");
return session.query(std::move(command)).then([] (auto result) {
	// ...
});
```

``` c++
cql::SessionFactory sessionFactory(
	cql::SessionConfiguration()
		.setDefaultKeySpace("system")
	cql::NodeCollection::create({
		cql::NodeConfiguration()
			.setAddress("127.0.0.1", 9043)
	}));
auto session = sessionFactory.getSession();
auto command = cql::Command("select * from batchlog").prepareQuery();
return session.query(std::move(command)).then([] (auto result) {
	// ...
});
```

Document: [Prepare](https://github.com/cpv-project/cpv-cql-driver/blob/master/docs/Prepare.md)

**Comment by dorlaor** [comment]
Great! Have you measured performance?
In general, this would make a fantastic blog on http://seastar.io/blog/
(and on Scylla)

**Comment by 303248153** [comment]
I will update the [Benchmark](https://github.com/cpv-project/cpv-cql-driver/blob/master/docs/Benchmark.md) before release 0.2.
Hopefully in this week.
